AllCops:
  NewCops: enable
  Exclude:
    - "bin/bundle"
    - "db/**/*"
    - "node_modules/**/*"
    - "data/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/environments/*"
    - "config/initializers/*"
