version: "3.7"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: indecision
      POSTGRES_PASSWORD: indecision
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis/data
  web:
    build: .
    command: sh -c 'yarn install && bundle install && bundle exec rails s -p 3000 -b "0.0.0.0"'
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/tmp
      - /tmp
      - /app/node_modules
      - /app/data
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: present
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: indecision_development
      POSTGRES_USERNAME: indecision
      POSTGRES_PASSWORD: indecision
      INDECISION_SMTP_ADDRESS: dev.rudi.lan.local
      INDECISION_SMTP_PORT: 2500
      INDECISION_SMTP_USERNAME: ""
      INDECISION_SMTP_PASSWORD: ""
      INDECISION_SMTP_AUTHENTICATION: ""
      INDECISION_SMTP_STARTTLS: ""
      S3_ACCESS_KEY: accesskey
      S3_SECRET_KEY: secretkey
      S3_REGION: "region"
      S3_IMAGES_BUCKET: "images"
      S3_ENDPOINT: "http://minio:9000"
      S3_FORCE_PATH_STYLE: "true"
    restart: always
  dbadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'rjsfeeney@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'nyeisme'
    ports:
      - "8081:80"
