apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "indecision.fullname" . }}-minio
  labels:
    app.kubernetes.io/name: {{ include "indecision.name" . }}
    helm.sh/chart: {{ include "indecision.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "indecision.name" . }}-minio
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "indecision.fullname" . }}-volume-claim
      containers:
        - name: "minio"
          image: {{ .Values.indecision.image_minio }}
          volumeMounts: 
            - mountPath: "/data"
              name: storage
          ports: 
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          envFrom: 
            - configMapRef: 
                name: {{ .Release.Name }}-configmap
          command: 
            - "/bin/sh"
            - "-ce"
            - "/usr/bin/docker-entrypoint.sh minio server /data --console-address ':9001'"
