apiVersion: v1
kind: Service
metadata:
  name: {{ include "indecision.fullname" . }}-svc
  labels:
    app.kubernetes.io/name: {{ include "indecision.name" . }}
    helm.sh/chart: {{ include "indecision.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "indecision.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "indecision.fullname" . }}-svc-minio
  labels:
    app.kubernetes.io/name: {{ include "indecision.name" . }}
    helm.sh/chart: {{ include "indecision.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: {{ include "indecision.name" . }}-minio
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "indecision.fullname" . }}-svc-redis
  labels:
    app.kubernetes.io/name: {{ include "indecision.name" . }}
    helm.sh/chart: {{ include "indecision.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "indecision.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
