apiVersion: v1
kind: Service
metadata:
  name: {{ include "indecision.fullname" . }}-svc
  labels:
    app.kubernetes.io/name: {{ include "indecision.name" . }}
    helm.sh/chart: {{ include "indecision.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "indecision.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
