name: Build and push image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v2
      - id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp/docker-registry
          key: docker-registry-buildkit-${{ hashFiles('Dockerfile') }}
      - name: Start registry
        run: docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2 && npx wait-on tcp:5000
      - name: Copy secret key into directory
        run: |
          echo $PRODUCTION_KEY >> config/master.key
        shell: bash
        env:
          PRODUCTION_KEY: ${{ secrets.PRODUCTION_CREDENTIALS_KEY }}
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.hexes.co.uk
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build image
        run: docker build . -t platform --cache-from=localhost:5000/platform --build-arg BUILDKIT_INLINE_CACHE=1
      - name: Cache image
        run: docker tag platform localhost:5000/platform && docker push localhost:5000/platform || true
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Push image
        run: docker tag platform registry.hexes.co.uk/indecision/indecision:latest && docker push registry.hexes.co.uk/indecision/indecision:latest
